### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by deadcoder0904** [Kruemelkatze/vscode-dashboard#27] opened 2019-11-02 12:42 UTC
Idk but it loads slow takes 1s-2s to load the Dashboard. Might be worth an improvement.

I checked `Extensions` page & tried loading some extensions & they do work instantly so there might be some speed improvement.

**Comment by Kruemelkatze** [comment] 2019-11-06 13:33
I already had a look on speeding things up. As far as I have come with this is that it's not my code that's taking this time. VSCode needs a few seconds to start up the extensions. Additionally, it takes some time to render the Webview (the custom UI option of VSCode that is used for the dashboard) everytime you open it. 

When you have a look on the [official webview extension sample](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample), that has nothing but a gif, you'll see that it also needs ~0.5s to load.

I took some performance measurements (using ```perf_hooks```) to see how my extension performs:
* Between ```1800 - 2200ms``` BEFORE my extension is even activated (nothing I can influence).
* All my startup code combined (registering events, loading data, creating webview and telling it to open) takes ```12.8 - 13.4ms```. That's in debug mode, so in the published extensions it should be even quicker. That's the time I could optimize.

I followed John Papa's blog entry to package and minify my extension with webpack. The script size went down from 65kB to 29kB. It won't have that much impact, but it looks "better" now.

So: As much as I'd like to speed things up, apparently that's out of the extension's reach. But I'd be more than happy if you could prove me wrong! :)

**Comment by deadcoder0904** [comment] 2019-11-06 13:38
Not sure I can help. Also, this is my first extension (even though I have 140+) that has a new tab. You can close it if you want :)

**Comment by Kruemelkatze** [comment] 2019-11-06 13:49
> Not sure I can help. Also, this is my first extension (even though I have 140+) that has a new tab. You can close it if you want :)

It's my first and only extension at all. ;)
I'll close this for now, but will post here if I find out anything.

**Closed by Kruemelkatze** 2019-11-06 13:49 UTC
Labels: enhancement

**Comment by deadcoder0904** [comment] 2019-11-06 13:50
Personally I love this extension because I'm using iTerm less & less. I have too many projects to open in VSCode & this extension sorts it out. Well done 👏

**Comment by richardtallent** [comment] 2019-11-19 20:43
First off, I **LOVE** this extension. It's exactly what I was looking for to help switch between projects.

I'm seeing a performance lag of about 4 seconds between the Dashboard tab appearing and its contents appearing.

My PC is a boring corporate Dell i5@2.4GHz laptop running Windows 7, and all of my projects being referenced are on the boot drive (SSD). I have 2 groups and a total of 11 project folders.

Oddly enough, on my home computer (2018 Mac Mini), the tab opens instantaneously, and it has about twice as many projects.

I cloned the repo and did a little testing on my Windows machine (my first time trying to work with extension code). The `showDashboard()` function is finishing in about 5ms, and the tab appears instantly, but the contents don't show up for another 4 seconds or so. So it does appear to be a problem with VS Code's rendering of the tab, not the extension. And since the rendered HTML string is only about 32KB, I can't think of a reason why a browser view would take so long to render it. Might be worth bringing up with the VS Code team.

I doubt it's related, since getDashboardContent executes quickly and without problems, but I am getting two errors while debugging the extension:
```
TS2339: Property 'cspSource' does not exist on type 'Webview'. (I get this one twice)
TS2339: Property 'asWebviewUri' does not exist on type 'Webview'.
```

**Comment by Kruemelkatze** [comment] 2019-11-19 23:13
Yes, I had a look into the performance multiple times (there are also some issues to that here on GitHub). Unfortunately, the cause of the delay is out of the extension's scope.

Concerning your two errors: CSP and the asWebviewUri property were introduced and recommended in one of the latest VSCode updates, as far as I remember. So that should be ok, I think. I'll have a look on this. :)
