### ISSUE TITLE
Custom color is not showing

### ISSUE THREAD

**Issue by agos** [Kruemelkatze/vscode-dashboard#5] opened 2018-09-28 13:41 UTC
When adding a project I was asked for a color, I choose the option for custom hex code, but it's not shown in the dashboard after the product is added

**Comment by Kruemelkatze** [comment] 2018-09-28 18:41
Thanks for reporting!
Can you post your projects data here? You can get it by running the Dashboard: Edit Projects command. That would help a lot.!

**Comment by agos** [comment] 2018-10-01 08:05
here is the projects data, I've redacted project names and local paths

```json
[
    {
        "id": "[redacted]0f975bi5hjmm0i9ce]",
        "name": "[redacted]",
        "path": "[redacted]",
        "imageFileName": null,
        "color": "D19F4E"
    },
    {
        "id": "[redacted]i6k7iefzejmm0iu4s",
        "name": "[redacted]",
        "path": "[redacted]",
        "imageFileName": null,
        "color": "D19F4E"
    },
    {
        "id": "[redacted]pre782o9ajmm0kit7",
        "name": "[redacted]",
        "path": "[redacted]",
        "imageFileName": null,
        "color": "var(--vscode-gitDecoration-untrackedResourceForeground)"
    },
    {
        "id": "[redacted]f0g8fvdtfjmq0a93i",
        "name": "[redacted]",
        "path": "[redacted]",
        "imageFileName": null,
        "color": "var(--vscode-gitDecoration-untrackedResourceForeground)"
    },
    {
        "id": "[redacted]6w0s5u525jmq0b716",
        "name": "[redacted]",
        "path": "[redacted]",
        "imageFileName": null,
        "color": "#fe57a1"
    }
]
```

**Comment by Kruemelkatze** [comment] 2018-10-02 20:37
Thanks! I'll look into that

**Comment by GammaGames** [comment] 2018-10-11 14:53
Doesn't the color need to be formatted like a hex code, so `#D19F4E`?

**Comment by Kruemelkatze** [comment] 2018-10-11 20:13
Update: I remembered incorrectly... The number has to be formatted like a hexcode with a leading # (just like @GammaGames said). The UI while even validates for that. 

I intended to support providing custom colors with and without #, but this would have just introduced additional checks while building the html.

So, just add a # to your custom colors. :)

**Comment by agos** [comment] 2018-10-12 08:59
@Kruemelkatze adding the leading `#` character has no effect. It was one of the things I tried and was even in the example file I posted last week. No color is showing: uppercase hex, lowercase hex, colours chosen by the list, nothing makes a difference.

**Comment by Kruemelkatze** [comment] 2018-10-12 17:38
@agos Interesting... I tried it yesterday and after adding ```#``` it worked just fine for me. I reopened the issue and will test this again on other systems! Sorry for the early closing and thanks for your persistence!

**Comment by Kruemelkatze** [comment] 2018-10-13 08:53
I just tested this on 3 systems (2x Windows 10, 1x Ubuntu 18.04) with different screen sizes and different font sizes in Windows. Projects 3-5 always showed the color and when adding a leading ´´´#´´´ to the first 2 project's colors, they worked as well. So I cannot reproduce this...

What system and VSCode version are you running?

**Comment by agos** [comment] 2018-11-08 14:07
@Kruemelkatze I'm running on MacOS 10.14, VSCode 1.28.2

**Comment by Kruemelkatze** [comment] 2019-02-14 22:55
Any news on this? Neither I nor some colleagues could reproduce that on Windows/Linux. Sadly, we don't have a Mac to test this out - in case it's a MacOS only issue.

**Comment by Kruemelkatze** [comment] 2019-06-27 11:26
Closing, as there has not been an update on this for more than 6 months.

**Closed by Kruemelkatze** 2019-06-27 11:26 UTC
