### ISSUE TITLE
Black cross on vscode start up

### ISSUE THREAD

**Issue by BCNelson** [Kruemelkatze/vscode-dashboard#35] opened 2020-03-20 15:57 UTC
![image](https://user-images.githubusercontent.com/5659892/77181388-d9322b00-6a90-11ea-91fc-bebe1b86d9c2.png)
I get this whenever I startup vscode. It however woks if I close it then open it from the command pallet.
I'm not sure what other information would be useful.

**Comment by Kruemelkatze** [comment] 2020-03-27 15:47
Oh, I had this only once and disregarded it.  I'll try to reproduce this, thanks for reporting!

**Comment by BCNelson** [comment] 2020-03-27 18:30
Is there any other information that I can provide

**Comment by Kruemelkatze** [comment] 2020-03-27 18:33
> Is there any other information that I can provide

Was thinking about that. Maybe you can open the "Webview Developer Tools" if this bug happens and see if there are any errors? Looks like the CSS does not load, maybe because of the content security policy.

**Comment by BCNelson** [comment] 2020-03-28 03:21
![image](https://user-images.githubusercontent.com/5659892/77813780-e3e05780-7070-11ea-93fe-4e710994fb37.png)

**Comment by Kruemelkatze** [comment] 2020-03-28 22:31
That helps a lot, thanks!

**Comment by Kruemelkatze** [comment] 2020-04-02 22:50
I could reproduce that on my machine on some occasions, but not regularly. Seems like [others have this issue too](https://github.com/microsoft/vscode/issues/89038). Looks like it's somewhere upstream.

![dashboard error](https://user-images.githubusercontent.com/5564731/78306926-e6e1b900-7544-11ea-97ad-85c96e132536.png)

**Comment by Kruemelkatze** [comment] 2020-07-29 16:34
The vscode team has marked this issue as resolved (https://github.com/microsoft/vscode/issues/89038#issuecomment-653258050) So I'm closing this. :-)

**Closed by Kruemelkatze** 2020-07-29 16:34 UTC
Labels: upstream
