### ISSUE TITLE
Crashing after update for VSCode v1.31.1

### ISSUE THREAD

**Issue by bugs181** [Kruemelkatze/vscode-dashboard#9] opened 2019-02-13 06:49 UTC
I've been using Dashboard for a while now and love it's simplicity. However, after the latest update of VSCode, it appears to crash. 

Opening VSCode:
```
Extension host terminated unexpectedly.
```

Running Dashboard from the command pallet gives me this error:
```
command 'dashboard.open' not found
```

Here's what Dev tools is giving me:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/levi/.vscode/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/levi/.vscode/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace


extensionService.ts:457 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ extensionService.ts:457
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:161  INFO no standard startup: not the explorer viewlet
```

I hope you find it useful and can push an update to this wonderful extension. Please let me know if you need more debugging info.

**Comment by Kruemelkatze** [comment] 2019-02-14 22:38
Thanks for reporting, I'll have a look on this as soon as i can!

**Comment by Kruemelkatze** [comment] 2019-02-14 22:52
I just tried to reproduce this problem on two computers running Win10 (build 1803), but everything worked fine. Also nobody from my company reported any errors - a bunch of my colleagues are using vscode-dashboard and most likely have the newest vscode update installed automatically.

Reading from your log, it looks like `ritwickdey.liveserver-5.3.1` [https://github.com/ritwickdey/vscode-live-server](https://github.com/ritwickdey/vscode-live-server) is causing some problems. I found [this issue](https://github.com/ritwickdey/vscode-live-server/issues/274) describing your exact problem.

Looks like that extension is somehow breaking the extension startup, so vscode-dashboard does not get initialized. I suggest you follow the solution in the linked issue. :)

I'm closing this, but will gladly reopen if the error persists.

**Closed by Kruemelkatze** 2019-02-14 22:52 UTC

**Comment by bugs181** [comment] 2019-02-15 06:33
Thanks so much for investigating this issue! I must apologize because I had assumed it was this extension, as it appeared it was the only one that wasn't working. I have confirmed that was the issue. Disabling Live Server extension fixed the problem. Again, I really appreciate your help and apologize for the inconvenience.
