### ISSUE TITLE
Garbles preferences dashboard.projectData

### ISSUE THREAD

**Issue by softstein** [Kruemelkatze/vscode-dashboard#48] opened 2020-07-03 08:39 UTC
On Osx 10.15.5 if fails to writethe project data. JSON value dashboard.projectData is garbled, plugin shows without styles.
However after some seconds dashboard shows up correctly.
No fancy preferencing, happens even if it is the only plugin.

![bug show 1](https://user-images.githubusercontent.com/6675234/86449323-50c25800-bd18-11ea-9468-dc5efb8c1dcc.png)
![bug show 2](https://user-images.githubusercontent.com/6675234/86449334-53bd4880-bd18-11ea-814e-65742ca186f6.png)

**Comment by Kruemelkatze** [comment] 2020-07-03 11:05
Thanks for reporting!

The dashboard showing up without styles is most likely the same issue as in #35, which happens due to an upstream bug in VSCode itself. But it should be fixed within one of the next VSCode releases.

Would you plese answer a few question to the mangling of the project data?
1) Have you had any projects in the dashboard before? (If so, I'm sorry if you lost them this way!).
2) You mentioned "writing the project data". Did you add/edit projects using the UI, commands or manually (via the edit command) when this happened?
3)  Is there any chance you accidentally introduced that linebreaks yourself? I'm using the VSCode API for the preferences. I never write to them directly, so I have no idea where this wrong format may come from...

Thank you. :)

**Comment by softstein** [comment] 2020-07-03 11:22
Welcome :)
No, it was the very first install. 
@1/2: First I just added some folders via the UI.  Then, when I looked into the preferences to define a new color I took note that there was a problem with the config file. Then I opened the .json by the VS preferences. 
@3: I can definitely exclude this bc it occurs reproducibly (on my system). I verified this by deactivating all my plugins but the buggy behavious persisted.
What seems interesting to me is that the linebreaks occur in null what should be a return value imho.
Also interesting that, even when it garbles the writing of the json data it somehow manages not to lose the data.

**Comment by Kruemelkatze** [comment] 2020-07-03 12:23
I see. And I could reproduce and find the problem (also happens on Windows)!

To why it messes up: Apparently, in one of the latest updates, VSCode formats a preference entry, when you try to edit it. The projectData is currently of type "array", so it expects some string of type "[]" and automatically inserts a linebreak after the first [. But if the value is "null", this linebreak is inserted after the n. I changed the preference type to nullable array and now it works. I'll publish an update to fix this today! :)

Why it does not mess up the dashboard UI: By default, the projects are stored in VSCode's global state, not in the user settings, to allow for different dashboards on multiple machines, even if settings are synced via the Settings Sync extension. If you want the projects to be stored in the preferences, there is a setting in the dashboard configuration section for this.

**Comment by Kruemelkatze** [comment] 2020-07-03 12:40
I just released v2.2.2 that fixes this. I'll reopen the issue if this issue persists in any way.

**Closed by Kruemelkatze** 2020-07-03 12:40 UTC

**Comment by softstein** [comment] 2020-07-03 13:36
Wow, your velocity redefines fast :)
Thank you!

**Comment by Kruemelkatze** [comment] 2020-07-03 13:51
> Wow, your velocity redefines fast :)
> Thank you!

Thank you! That's one of the upsides of being self-employed and having interesting side projects. ;)
