### ISSUE TITLE
Custom SSH Key for SSH Targets

### ISSUE THREAD

**Issue by bearbytes** [Kruemelkatze/vscode-dashboard#33] opened 2020-03-05 10:18 UTC
Hi Kruemelkatze,
greetings from Graz, and thank you for building this useful extension :)

I tried using this for my many remote connections, unfortunately right now it only works when the remote authenticates against my default ssh key `~/.ssh/id_rsa`.

It would be a great improvement if you could also specify a path to a different identity file, or pick up the configuration from `~/.ssh/config`, like the remote SSH extension does.

**Comment by Kruemelkatze** [comment] 2020-03-27 15:50
Hello there :)
Good to see that other "local" people use this too!

I'll have a look on this! As far as I remember (build it a while ago), the dashboard only executes the "open XYZ" command, all the ssh handling is done by the SSH Extension.

**Comment by Kruemelkatze** [comment] 2020-04-02 22:41
Hey, @bearbytes!

I just tried to reproduce this with MYPAGE.xyz:
1) Added ```MYPAGE.xyz``` as SSH Target project.
2) Opened the ssh project. No problems, no password check (as it got the ssh key in default position).
3) Moved my ssh key from ```~/.ssh/id_rsa``` to ```~/.ssh/test/id_rsa```
4) Opened the ssh project. I was asked for my PW, as the key was now not found. So far, so good.
5) Added the entry ```IdentityFile ~/.ssh/test/id_rsa``` to the config section in ```~/.ssh/config```
6) Opened the ssh project. Worked again, the ssh client found the moved key.

So: The remote extension picked up the configuration just fine for me (under Windows 10), latest versions of VSCode and the SSH Remote extension.

Maybe you can recheck this on your side. Can you ssh to the target in the command line without problems?

I dare to say that this is not an issue with the dashboard extension. The extension simply issues the command for opening the ssh target, nothing more. I don't fiddle with any opening behavior or ssh keys. :)

**Comment by Kruemelkatze** [comment] 2020-06-30 11:46
Since neither me nor my testers could reproduce this and there wasn't any activity in nearly 3 months, I'm closing this.

**Closed by Kruemelkatze** 2020-06-30 11:46 UTC
Labels: question

**Comment by SheepDomination** [comment] 2023-12-24 14:13
> Hi Kruemelkatze, greetings from Graz, and thank you for building this useful extension :)
> 
> I tried using this for my many remote connections, unfortunately right now it only works when the remote authenticates against my default ssh key `~/.ssh/id_rsa`.
> 
> It would be a great improvement if you could also specify a path to a different identity file, or pick up the configuration from `~/.ssh/config`, like the remote SSH extension does.

If I understand correctly you want to use an SSH key to authenticate connecting to a dashboard (workspace) so that it will only open when the key is authenticated ?
